import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import Header from '@/components/Header';

const lato = Lato({
  subsets: ["latin"],
  weight: ['400', '700']
});

export const metadata: Metadata = {
  title: "Banco Itau",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
      <body className={lato.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
